/**
 * @file board_wifi.h
 * @brief Drivers and Failover Wi-Fi manager for ESP-IDF v6.0+.
 * @author Filipe Mesel Lobo Costa Cardoso
 * @date 2026-09-05
 */

#ifndef BOARD_WIFI_H
#define BOARD_WIFI_H

#include "esp_err.h"
#include "esp_event.h"

#ifdef __cplusplus
extern "C" {
#endif

#define WIFI_MAX_CREDENTIAL_LEN  64
#define WIFI_MAX_FAILOVER_RETRIES 3

typedef struct {
    char ssid[WIFI_MAX_CREDENTIAL_LEN];
    char password[WIFI_MAX_CREDENTIAL_LEN];
} wifi_credential_t;

/**
 * @brief Event identifiers generated by the Wi-Fi Manager.
 */
typedef enum {
    BOARD_WIFI_EVENT_CONNECTED,      /**< Successfully connected and obtained IP address. */
    BOARD_WIFI_EVENT_FAILOVER_EXHAUSTED, /**< Tried all N networks 3 times without success. */
    BOARD_WIFI_EVENT_DISCONNECTED    /**< Connection lost after establishment. */
} board_wifi_event_id_t;

ESP_EVENT_DECLARE_BASE(BOARD_WIFI_EVENTS);

/**
 * @brief Initializes the underlying Netif and Wi-Fi stack.
 * 
 * @return esp_err_t ESP_OK on success.
 */
esp_err_t board_wifi_init(void);

/**
 * @brief Sets the user dynamic Wi-Fi credential (retrieved from FRAM).
 * 
 * @param cred Pointer to credential structure containing SSID and password.
 * @return esp_err_t ESP_OK on success, ESP_ERR_INVALID_ARG if NULL.
 */
esp_err_t board_wifi_set_dynamic_credential(const wifi_credential_t *cred);

/**
 * @brief Starts the failover connection loop (Dynamic Net -> Fallback N-1 Nets).
 * 
 * @note Tries each network up to 3 times before switching to the next.
 * @return esp_err_t ESP_OK if execution sequence started.
 */
esp_err_t board_wifi_start_failover_connect(void);

/**
 * @brief Stop Wi-Fi driver and release hardware resource.
 * 
 * @return esp_err_t ESP_OK on success.
 */
esp_err_t board_wifi_stop(void);

#ifdef __cplusplus
}
#endif

#endif // BOARD_WIFI_H